### ISSUE TITLE
Lazy loading of Properties

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#275]
The Mimir profiler is... not the fastest.  The way it is currently set up, properties are always computed when a table is created.  This is not only slow, but completely useless for cells that do not show the dataset by default, or if the user isn't going to look at the cell results.

One way would be to disable profiling for some view types.  

A better way would be to have properties data lazily loaded.  For example, we could expose a properties or profile endpoint on Mimir and only ping it when properties are required.  Another way would be to do this in the UI.  Give the UI the tools to trigger the profiler (e.g., when someone clicks on one of the profiler views).

I'm creating this ticket to start a discussion: @mrb24 @soniacq @maqzi @heikomuller @lordpretzel @julianafreire 

## Tasks
- [x] Modify get dataset routes in **web-api** to have a `profile` get argument.
- [x] Modify get table route in **mimir** to have a `profile` JSON argument
- [ ] Modify **data-mart** profiler to add a `is_profiled` field: An array listing categories of profiler data computed.
- [x] Modify **mimir** profiler to add a `is_profiled` field: An array listing categories of profiler data computed.
- [x] Move profile computation in **mimir** from Catalog.put to get table route
- [x] Add in logic to de-duplicate profile computation in **mimir**
- [x] Modify **web-ui** profile view to check if properties are present (presence of an `is_present` field) and asynchronously (block the profile view, not the entire screen) load them if not using the web-api dataset route with `force_properties`.

**Comment by okennedy** [comment]
## Tasks
- [ ] Modify get dataset routes in **web-api** to have a `force_properties` get argument.
- [ ] Modify get table route in **mimir** to have a `force_properties` get argument
- [ ] Modify **data-mart** profiler to add a `is_profiled` field: An array listing categories of profiler data computed.
- [ ] Modify **mimir** profiler to add a `is_profiled` field: An array listing categories of profiler data computed.
- [ ] Move profile computation in **mimir** from Catalog.put to get table route
- [ ] Add in logic to de-duplicate profile computation in **mimir**
- [ ] Modify **web-ui** profile view to check if properties are present (presence of an `is_present` field) and asynchronously (block the profile view, not the entire screen) load them if not using the web-api dataset route with `force_properties`.

**Comment by okennedy** [comment]
@maqzi 's https://github.com/VizierDB/web-ui/pull/290 , should largely resolve this.  

Is there a corresponding update to the data-mart profiler @soniacq ?
